# Exercícios

## 1) Crie uma classe que irá modelar características geométricas de um círculo. Deverá implementar os métodos:
        -> Área 
        -> Perímetro
## Utilize atributos de classe e de instância apropriados. Crie um inicializador e métodos.
$area = \pi*r^2$

$perimetro = 2*\pi*r$

In [28]:
# resposta 1
import math

class Circulo:
    pi = math.pi
    
    def __init__(self, raio):
        self.raio = raio
        
    def area(self,raio):        
        self.raio = raio
        print('dado o raio ',raio,' a area é', Circulo.pi * (raio**2))

    def perimetro(self, raio):
        self.raio = raio
        print('dado o raio ',raio,' a perimetro é', 2 * Circulo.pi * raio)
      
objeto.area(4)
objeto.perimetro(4)


dado o raio  4  a area é 50.26548245743669
dado o raio  4  a perimetro é 25.132741228718345


## 2) Crie uma classe chamada matemática que conterá duas classes: trigonométrica e algébrica. Defina dentro da classe trigonométrica as seguintes funções:
    -> seno
    -> cosseno
    -> tangente
## Defina dentro da classe algébrica as seguintes funções: 
    -> soma
    -> subtração
    -> multiplicação
    -> divisão
## Cada função deverá receber array e retornar array

In [143]:
# resposta 2
import numpy as np

class matematica:
    class trigonometria:
        def seno(self,val):
            print (np.sin(val))
    
        def coseno(self,val):
            print (np.cos(val))
        
        def tangente(self,val):
            print(np.tan(val))

    class algebrica:
        def soma(self, A1, A2):
            print(A1 + A2)
        
        def subtracao(self, A1, A2):
            print(A1 - A2)
            
        def multiplicacao(self,A1, A2):
            print(A1 * A2)

        def divisao(self, A1, A2):
            print(A1 / A2)
            
        
A1 = np.array([1,2,3,4,5])
A2 = np.array([6,7,8,9,10])
ob1 = matematica.trigonometria()        
ob1.seno(A1)
ob1.coseno(A1)
ob1.tangente(A1)


ob2 = matematica.algebrica()
ob2.soma(A1,A2)
ob2.subtracao(A1,A2)
ob2.multiplicacao(A1,A2)
ob2.divisao(A1,A2)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[ 0.16666667  0.28571429  0.375       0.44444444  0.5       ]


## 3) Dados 2 arrays, A e B, remova de A todo elemento pertencente a B

In [141]:
# resposta 3
A = np.array([1,2,3,4,5,6,7,8])
B = np.array([1,2,8])

#vai cavalo
print (A[B[np.searchsorted(B,A)] !=  A])

[3 4 5 6 7]


## 4) Crie uma função que recebe um array, um inteiro n e um inteiro m e que retorne outro array contendo elementos que estão entre os valores n e m do array recebido pela função. 

In [148]:
# resposta 4

def BuscaDado(A, N, M):
    B = np.arange(N,M)    
    print(np.intersect1d(A,B))
                              
A = np.array([1,1,2,3,3,3,4,5,6,7,8,8])
BuscaDado(A, 2, 5)




[2 3 4]


## 5) Escreva uma função que recebe um vetor e um inteiro. Compare cada elemento desse vetor com o número inteiro. Se o elemento do vetor for maior, retorne a diferença entre eles, caso contrário, retorne a soma.

In [149]:
# resposta 5

def compara(Vet,Num):
    print(np.where(Vet > Num, Vet - Num, Vet +Num))
            
A = np.array([1,1,2,3,3,3,4,5,6,7,8,8])
B = 4

compara(A,B)

[5 5 6 7 7 7 8 1 2 3 4 4]


## 6) Dada a seguinte matriz:
    -> [ 8,1,7
         4,3,9
         5,2,6]
## escreva uma função que retorne a matriz ordenada por um dos eixos. utilize a função built-in sorted para realizar a ordenação

In [139]:
# resposta 6

def ordena_matriz(Matriz):
    print(np.apply_along_axis(sorted,1,arr = matriz))
    
matriz = np.array([[8,1,7],[4,3,9],[5,2,6]])    
ordena_matriz(matriz)

[[1 7 8]
 [3 4 9]
 [2 5 6]]


In [127]:
help (sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

